"""Research prompt assembly.

Ported from the v34 archive (legacy/aekovera/main.py, prompting section).
The v4 judge rulebook ships as package data next to the gate that loads it.
"""

import json

from review_hub.engine import addmissing
from review_hub.engine import decision as decision_v4
from review_hub.engine.fields import FIELDS
from review_hub.jsonutil import safe_text

SYSTEM_PROMPT = (
    "You are a strict data-verification agent for a US food & beverage CPG supply-chain "
    "database. You cannot browse the web; you judge only the evidence supplied in the "
    "prompt. You never invent facts, never guess contact details, and never assume a "
    "company is in scope. When the evidence is insufficient, follow the rulebook: "
    "PARK or RE_ENRICH a real in-scope company, REJECT only out-of-scope or no-trace entries. "
    "You reply with a single valid JSON object and nothing else."
)


def build_rules_block(browsing=False):
    """The v4 judge rulebook (prompts/judge_v4.md).

    v13: the whole rules + schema block is now the founder-aligned v4 rulebook,
    kept in one editable file rather than embedded here, so it can be changed
    without touching code. Its section 10 already defines the output schema,
    which is why build_schema_block() is now only a strict-JSON reminder.
    """
    return decision_v4.load_prompt(browsing=browsing)


def build_record_payload(record, evidence_text="", compact=False):
    """The per-record part of the prompt - the only thing that changes.

    When compact=True (Project mode) the payload is deliberately dense:
    single-line JSON for fields, truncated page context, minimal links,
    and a hard character target so ChatGPT chats stay usable longer.
    """
    evidence_block = ""
    if evidence_text:
        evidence_block = "\n" + evidence_text.strip() + "\n"

    editable = record.get("editable_fields") or FIELDS
    readonly = record.get("readonly_fields") or []
    readonly_block = ""
    if readonly:
        readonly_block = (
            "READ-ONLY (context only, never change): " + ", ".join(readonly) + "\n"
        )

    # Dense single-line field dump for compact mode (saves hundreds of chars).
    if compact:
        fields_json = json.dumps(record["fields"], ensure_ascii=False, separators=(",", ":"))
        # Cap page context hard so the whole paste stays near the 600-800
        # char target that keeps Project chats healthy longer.
        page_ctx = safe_text(record.get("page_context"))[:700]
        missing = addmissing.render_for_prompt(record.get("missing_fields") or [])
        if missing:
            missing = missing.strip() + "\n"
        # Links are omitted in compact mode: the website field + page context
        # already give the model what it needs, and dropping them saves ~200-400
        # chars that would otherwise push every paste over the healthy limit.
        return (
            f"CURRENT RECORD (UNTRUSTED):\n{fields_json}\n\n"
            f"EDITABLE: {', '.join(editable)}\n"
            f"{readonly_block}"
            f"PAGE CONTEXT (UNTRUSTED):\n{page_ctx}\n\n"
            f"{missing}"
            f"{evidence_block}"
        )

    # Full (non-compact) version kept for the non-Project path.
    return f"""CURRENT RECORD (UNTRUSTED):
{json.dumps(record["fields"], indent=2, ensure_ascii=False)}

EDITABLE FIELDS (you may propose changes ONLY to these keys):
{", ".join(editable)}

{readonly_block}LINKS GENERATED BY THE CURRENT RECORD (ALSO UNTRUSTED):
{json.dumps(record["links"], indent=2, ensure_ascii=False)}

PAGE CONTEXT (UNTRUSTED):
{record["page_context"]}

{addmissing.render_for_prompt(record.get("missing_fields") or [])}
{evidence_block}"""


def build_schema_block():
    """Closing reminder. The schema itself lives in section 10 of the rulebook."""
    return (
        "\n\nReturn exactly one JSON object matching section 10. "
        "No prose, no markdown fences. decision must be exactly one of "
        "ACCEPT, PARK, RE_ENRICH, REJECT.\n"
    )


def build_research_prompt(record, evidence_text="", compact=False, browsing=False):
    """Assemble the full prompt.

    compact=True omits the static rules and schema, for use with a ChatGPT
    Project that already carries them in its custom instructions. The per-record
    payload is deliberately kept under ~800 characters whenever possible so
    that a single Project chat stays usable for more records before drift.
    """
    payload = build_record_payload(record, evidence_text, compact=compact)
    if compact:
        # Hard reset line is critical: ChatGPT Projects slowly dilute
        # instructions after many turns. Starting every paste with an explicit
        # "this is a brand-new independent record" keeps the model honest longer.
        hard_reset = (
            "NEW RECORD. Ignore all previous companies and all prior answers. "
            "Follow the Project custom instructions exactly. "
            "Search the web for this company and open its website and contact page "
            "BEFORE deciding; nothing has been fetched for you. "
            "Output ONLY valid JSON matching the schema. No markdown, no prose.\n\n"
        )
        return hard_reset + payload
    return build_rules_block(browsing=browsing) + "\n" + payload + "\n" + build_schema_block()
